### ISSUE TITLE
Retry No. ==> 3 : Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by AndresQuiVal** [iSarabjitDhiman/InstaGPy#1]
I have this error when trying to login @iSarabjitDhiman 
`
Retry No. ==> 3 : Expecting value: line 1 column 1 (char 0)`

my code:
```
while not insta.logged_in():
    insta.login(
        username="@@@",
        password="@@@"
    )
```

**Comment by iSarabjitDhiman** [comment]
Hey @AndresQuiVal 

Try installing this package and the retry with the insta login
```python
pip install Brotli==1.0.9
```

Let me know if the issue still persists.

**Comment by AndresQuiVal** [comment]
Hello @iSarabjitDhiman , I installed the package version you told me and yet the error persists. Btw I'm using MacOS

**Comment by iSarabjitDhiman** [comment]
> Hello @iSarabjitDhiman , I installed the package version you told me and yet the error persists. Btw I'm using MacOS

I am not able to replicate the issue on my end, could u please attach the trackback/error log? Make sure to hide your account credentials.

**Comment by AndresQuiVal** [comment]
I think I solved, just changed my network and solved! thanks @iSarabjitDhiman

**Comment by iSarabjitDhiman** [comment]
> I think I solved, just changed my network and solved! thanks @iSarabjitDhiman 

Great. Thanks for the update. Yeah I think it was your IP address.
