### ISSUE TITLE
Couldn't login, Try again...

### ISSUE THREAD

**Issue by arthwist** [iSarabjitDhiman/InstaGPy#3]
Hello, when I try to connect to my Insta account I get the following error message:

Couldn't Login, Try again...
{'message': 'Please wait a few minutes before you try again.', 'require_login': True, 'status': 'fail'}

I've tried with several accounts but I still have the same problem, no A2F activated.

**Comment by iSarabjitDhiman** [comment]
> Hello, when I try to connect to my Insta account I get the following error message:
> 
> Couldn't Login, Try again...
> {'message': 'Please wait a few minutes before you try again.', 'require_login': True, 'status': 'fail'}
> 
> I've tried with several accounts but I still have the same problem, no A2F activated.
> 
> 

Hey, any of the following might be a reason.
- You have been scraping for a while, you need to wait for some time before u can log in again. 
- They might have blocked your IP for a short period of time, so you can try changing your IP address.

Just trying logging in with the web browser.

This InstaGPy script needs some updates, actually I am quite busy these days, so it may take me some time to update the code. I would suggest you to try some other scripts from the github in the meantime. 

Good luck.

**Comment by arthwist** [comment]
Hello, I did what you said but without success... I hope you can solve the problem. Thank you!

**Comment by iSarabjitDhiman** [comment]
When u tried to log in with the browser, did it work ? If yes, copy the session_id from the cookies and use the InstaGPy().generate_session(session_id="session id here") method to generate a session without manually logging in. 

Let me know how it goes.

**Comment by arthwist** [comment]
Thanks, it works now with your solution!
