### ISSUE TITLE
Get user data function not working

### ISSUE THREAD

**Issue by ackermenn** [iSarabjitDhiman/InstaGPy#5]
Get user data isn't fetching the phone numbers and emails of the specified usernames please any solution to get rid of this???

**Comment by iSarabjitDhiman** [comment]
Hey @ackermenn 
I just checked and its working. Whats the username you are trying to fetch phone number from? I just want to point out that this doesnt work for any private data, so you cannot find the emails attached to an account. But you can collect emails/phones from any professional/business account (the contact info embedded into the blue colored "contact" button on a user's profile).

Hope I explained it well.
